
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    container_name: time-tracker-postgres-container
    networks:
      - portfolio-project-network
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shubham
      POSTGRES_DB: time-tracker
  pg-admin:
    image: dpage/pgadmin4:6
    ports:
      - 5050:5050
    container_name: time-tracker-pgadmin-container
    networks:
      - portfolio-project-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: shubham
      PGADMIN_LISTEN_PORT: 5050
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    container_name: time-tracker-server-container
    networks:
      - portfolio-project-network
    env_file: ./server/.env.local
    volumes:
      - ./server:/app
    depends_on:
      - postgres
  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    container_name: time-tracker-client-container
    networks:
      - portfolio-project-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
networks:
  portfolio-project-network:
volumes:
  postgresData:
